CREATE TABLE IF NOT EXISTS groom_father (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    first_name TEXT NOT NULL,
    last_name TEXT NULL,
    alias TEXT NULL,
    identity_id VARCHAR(16) NOT NULL,
    birth_place TEXT NULL,
    birth_date DATE NULL,
    job TEXT NULL,
    nationality TEXT NOT NULL DEFAULT 'Indonesia',
    religion TEXT NOT NULL DEFAULT 'ISLAM',
    deceased BOOLEAN NOT NULL DEFAULT FALSE,
    province_code TEXT NULL,
    province_name TEXT NULL,
    city_code TEXT NULL,
    city_name TEXT NULL,
    district_code TEXT NULL,
    district_name TEXT NULL,
    sub_district_code TEXT NULL,
    sub_district_name TEXT NULL,
    address TEXT NULL,
    rw TEXT NULL,
    rt TEXT NULL,
    zip_code TEXT NULL,

    version INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by TEXT DEFAULT 'system',
    deleted BOOLEAN DEFAULT FALSE,
    deleted_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_by TEXT DEFAULT 'system'
);