CREATE TABLE defendant (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    first_name TEXT,
    last_name TEXT,
    alias TEXT,
    birth_place TEXT,
    birth_date DATE,
    age INTEGER,
    religion TEXT,
    nationality TEXT,
    identity_type TEXT,
    identity_number TEXT,
    marital_status TEXT,
    education TEXT,
    job TEXT,
    phone_number TEXT,
    province_code TEXT,
    province_name TEXT,
    city_code TEXT,
    city_name TEXT,
    district_code TEXT,
    district_name TEXT,
    sub_district_code TEXT,
    sub_district_name TEXT,
    address TEXT,
    rw TEXT,
    rt TEXT,
    zip_code TEXT,

    version INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by TEXT DEFAULT 'system',
    deleted BOOLEAN DEFAULT FALSE,
    deleted_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_by TEXT DEFAULT 'system'
);